environments:
  lab:
    api_base_url: "https://lab-sn.emso.vn/api/v1"
    timeout: 15
    headers:
      accept: "application/json, text/plain, */*"
      accept-language: "vi-VN,vi;q=0.9,fr-FR;q=0.8,fr;q=0.7,en-US;q=0.6,en;q=0.5"
      origin: "https://lab-fe.emso.vn"
      priority: "u=1, i"
      referer: "https://lab-fe.emso.vn/"
      sec-ch-ua: "\"Not)A;Brand\";v=\"8\", \"Chromium\";v=\"138\", \"Google Chrome\";v=\"138\""
      sec-ch-ua-mobile: "?0"
      sec-ch-ua-platform: "\"Windows\""
      sec-fetch-dest: "empty"
      sec-fetch-mode: "cors"
      sec-fetch-site: "same-site"
      user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
  dev:
    api_base_url: "https://api.dev.example.com"
    timeout: 10
    headers:
      accept: "application/json, text/plain, */*"
      content-type: "application/json"
  staging:
    api_base_url: "https://api.staging.example.com"
    timeout: 15
    headers:
      content-type: "application/json"
  production:
    api_base_url: "https://api.example.com"
    timeout: 20
    headers:
      content-type: "application/json"